c-pallets/file-bank/src/lib.rs
- feat: compare the two pricing
=> Improve the pricing mechanism

.gitignore, Cargo.lock, c-pallets/file-map/Cargo.toml, c-pallets/file-map/src/lib.rs, c-pallets/file-map/src/mock.rs, c-pallets/file-map/src/tests.rs
completed the pallet-file-map tests
=> File map tests

c-pallets/sminer/Cargo.toml, c-pallets/sminer/src/lib.rs, c-pallets/sminer/src/mock.rs, c-pallets/sminer/src/tests.rs
Update the sminer pallet unit tests.
=> style: update sminer pallet unit tests

c-pallets/file-bank/src/mock.rs, c-pallets/segment-book/Cargo.toml, c-pallets/segment-book/src/mock.rs, c-pallets/segment-book/src/tests.rs
=> update segment book tests

Cargo.lock, README.md, c-pallets/file-bank/src/lib.rs, c-pallets/file-map/src/lib.rs, c-pallets/segment-book/src/lib.rs, c-pallets/sminer/Cargo.toml, c-pallets/sminer/src/lib.rs
- Troubleshooting and modifying the hidden dangers caused by the use of expect and unwrap methods
- update Readme, added cess-bootstrap module.
=> Solve hidden troubles in code

c-pallets/file-bank/src/lib.rs, c-pallets/file-bank/src/mock.rs, c-pallets/file-bank/src/tests.rs, c-pallets/sminer/src/lib.rs, node/src/chain_spec.rs, node/src/command.rs, node/src/main.rs, node/src/primitives.rs, node/src/service.rs, runtime/src/lib.rs
=> style: processing warnings

c-pallets/file-bank/src/lib.rs
- Synchronize the code of the current test network
=> Synchronize the code of the current test network

.github/workflows/build-and-test.yml, README.md
use GitHub Actions for auto build
=> use GitHub Actions for auto build

c-pallets/sminer/README.md
update the Sminer module readme
=> Heyworld88 patch 3

Cargo.lock, c-pallets/file-bank/Cargo.toml, c-pallets/file-bank/src/benchmarking.rs, c-pallets/file-bank/src/mock.rs, c-pallets/file-bank/src/tests.rs, c-pallets/file-map/Cargo.toml, c-pallets/file-map/src/mock.rs, c-pallets/segment-book/Cargo.toml, c-pallets/segment-book/src/mock.rs, c-pallets/segment-book/src/tests.rs, c-pallets/sminer/src/lib.rs, c-pallets/sminer/src/mock.rs, c-pallets/sminer/src/tests.rs
- test: fix test and benchmark
=> test: fix tests and benchmark

Cargo.lock, c-pallets/file-bank/Cargo.toml, c-pallets/file-bank/README.md, c-pallets/file-bank/src/lib.rs, c-pallets/file-bank/src/migrations.rs, c-pallets/file-bank/src/mock.rs, c-pallets/file-bank/src/tests.rs, c-pallets/file-map/README.md, c-pallets/file-map/src/lib.rs, c-pallets/file-map/src/tests.rs, c-pallets/segment-book/src/mock.rs, c-pallets/segment-book/src/tests.rs, c-pallets/sminer/README.md, c-pallets/sminer/src/tests.rs, node/Cargo.toml, node/src/cli.rs, node/src/command.rs, runtime/Cargo.toml, runtime/src/lib.rs
- add try-runtime
- update readme.md
- fix warn
=> Test migrations

c-pallets/file-bank/README.md
- update readme of file-bank pallet
=> update: readme file-bank

Cargo.lock, c-pallets/file-bank/Cargo.toml, c-pallets/file-bank/src/lib.rs, c-pallets/file-bank/src/migrations.rs, c-pallets/file-bank/src/types.rs, c-pallets/file-map/Cargo.toml, c-pallets/segment-book/Cargo.toml, c-pallets/segment-book/src/lib.rs, c-pallets/segment-book/src/types.rs, c-pallets/sminer/Cargo.toml, c-pallets/sminer/src/lib.rs, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
- fix 0.5.2 bug
- specification version
=> 0.5.2 fixbug

c-pallets/sminer/README.md
=> style: update readme

c-pallets/cacher/src/benchmarking.rs, c-pallets/cacher/src/lib.rs, c-pallets/cacher/src/tests.rs, c-pallets/cacher/src/types.rs
fix the problems raised in the SBP M3 review
=> SBP M3 fix

Cargo.lock, c-pallets/staking/src/pallet/impls.rs, c-pallets/staking/src/pallet/mod.rs, node/src/chain_spec.rs, runtime/src/lib.rs
* feat: add stake_score in election
* fix: merge conflics
* fix: https://github.com/paritytech/substrate/pull/13804
=> feat: add stake_score in validator election (#125)

c-pallets/audit/src/lib.rs, c-pallets/file-bank/Cargo.toml, c-pallets/file-bank/src/constants.rs, c-pallets/file-bank/src/functions.rs, c-pallets/file-bank/src/lib.rs, c-pallets/file-bank/src/types.rs, c-pallets/sminer/src/constants.rs, c-pallets/sminer/src/lib.rs, c-pallets/storage-handler/src/lib.rs, c-pallets/tee-worker/src/lib.rs, primitives/common/src/lib.rs, runtime/src/lib.rs
- fixed some bugs in the test version
=> 0.6.0 test

c-pallets/audit/src/lib.rs, c-pallets/oss/src/lib.rs, c-pallets/staking/src/pallet/mod.rs, primitives/enclave-verify/src/lib.rs, runtime/src/lib.rs
- Change the return result of abnormal situations in the DeOSS authorization interface.
- Fix the issue of generating challenges that repeatedly report events.
=> 0.7.0 patch 1

c-pallets/audit/src/constants.rs, c-pallets/audit/src/lib.rs, c-pallets/file-bank/src/lib.rs, c-pallets/sminer/src/helper.rs, c-pallets/sminer/src/lib.rs, c-pallets/sminer/src/tests.rs, runtime/src/lib.rs
- Changed event name.
- Update idle prove calculate rate.
- Update verify duration calculate rule.
=> style: update event name and idle prove rate

c-pallets/audit/src/lib.rs
=> Correct the log text

Cargo.lock, c-pallets/audit/Cargo.toml, c-pallets/file-bank/src/lib.rs, c-pallets/sminer-reward/Cargo.toml, c-pallets/sminer-reward/src/lib.rs, c-pallets/sminer/Cargo.toml, c-pallets/sminer/src/functions.rs, c-pallets/sminer/src/helper.rs, c-pallets/sminer/src/lib.rs, c-pallets/storage-handler/Cargo.toml, c-pallets/storage-handler/src/lib.rs, runtime/Cargo.toml, runtime/src/lib.rs
- economic model requirements change.
=> feat: economic model requirements change

c-pallets/audit/src/lib.rs, c-pallets/oss/src/lib.rs, c-pallets/oss/src/types.rs
- adding domain fields to oss.
- cancel the penalty mechanism for idle data in random challenges.
=> 0.7.4 challenge punish cancel

c-pallets/audit/src/lib.rs, c-pallets/audit/src/types.rs, c-pallets/sminer/src/constants.rs, c-pallets/sminer/src/helper.rs, c-pallets/sminer/src/lib.rs, primitives/common/src/lib.rs, runtime/src/lib.rs
- Fix some bugs found during this test
=> 0.7.4 test

c-pallets/file-bank/src/functions.rs, c-pallets/file-bank/src/lib.rs, c-pallets/file-bank/src/types.rs, c-pallets/sminer/src/lib.rs, primitives/common/src/lib.rs
- New file upload process changes.
=> 0.7.5 upload file

c-pallets/tee-worker/src/lib.rs, c-pallets/tee-worker/src/types.rs, primitives/common/src/lib.rs
- Modify the verification rules of the tee registration interface.
- Add tee registration interface parameters.
=> feat: add end point param in tee register  interface

Cargo.lock, c-pallets/file-bank/src/constants.rs, c-pallets/file-bank/src/functions.rs, c-pallets/file-bank/src/impls/dealimpl.rs, c-pallets/file-bank/src/impls/receptionist.rs, c-pallets/file-bank/src/lib.rs, c-pallets/sminer/src/lib.rs, c-pallets/storage-handler/src/lib.rs, c-pallets/storage-handler/src/types.rs, node/Cargo.toml, runtime/Cargo.toml, runtime/src/lib.rs
- Fix some bugs in testing.
- Optimize the purchase space order function.
=> 0.7.5 test

c-pallets/audit/src/lib.rs, c-pallets/file-bank/src/functions.rs, c-pallets/file-bank/src/lib.rs, c-pallets/sminer/src/helper.rs, c-pallets/sminer/src/lib.rs, c-pallets/storage-handler/src/lib.rs, runtime/src/lib.rs
=> 0.7.5 fix bug

Cargo.lock, pallets/audit/src/lib.rs, pallets/cess-treasury/Cargo.toml, pallets/cess-treasury/src/constants.rs, pallets/cess-treasury/src/lib.rs, pallets/sminer/src/constants.rs, pallets/sminer/src/functions.rs, pallets/sminer/src/helper.rs, pallets/sminer/src/lib.rs, pallets/sminer/src/types.rs, standalone/chain/runtime/src/lib.rs
- modification of reward and punishment
=> feat: modification of reward and punishment

pallets/file-bank/src/constants.rs, pallets/file-bank/src/functions.rs, pallets/file-bank/src/impls/dealimpl.rs, pallets/file-bank/src/impls/receptionist.rs, pallets/file-bank/src/lib.rs, pallets/file-bank/src/types.rs, pallets/sminer/src/helper.rs, pallets/sminer/src/lib.rs
- feat: file upload and calculate tag
=> 0.7.6 file upload and calculate tag

standalone/chain/node/src/service.rs
@yeousunn @swowk @ytqaljn This is the fix on the grandpa RPC endpoint
=> Fix on the grandpa RPC endpoint connection

Cargo.lock, pallets/audit/Cargo.toml, pallets/audit/README.md, pallets/audit/src/lib.rs, pallets/cess-treasury/Cargo.toml, pallets/file-bank/Cargo.toml, pallets/file-bank/README.md, pallets/file-bank/src/impls/dealimpl.rs, pallets/file-bank/src/impls/receptionist.rs, pallets/file-bank/src/lib.rs, pallets/sminer/Cargo.toml, pallets/sminer/README.md, pallets/sminer/src/helper.rs, pallets/sminer/src/lib.rs, pallets/storage-handler/README.md, pallets/storage-handler/src/lib.rs, pallets/tee-worker/Cargo.toml, pallets/tee-worker/src/lib.rs, standalone/chain/node/Cargo.toml, standalone/chain/runtime/Cargo.toml, standalone/chain/runtime/src/lib.rs
=> 0.7.6 fix bug

pallets/audit/src/lib.rs, pallets/tee-worker/src/functions.rs, pallets/tee-worker/src/lib.rs, standalone/chain/runtime/src/lib.rs
- feat: add some auxiliary functions to facilitate debugging
=> feat: add some auxiliary functions to facilitate debugging

pallets/audit/src/constants.rs, pallets/audit/src/lib.rs, pallets/cess-treasury/src/lib.rs, pallets/sminer/src/functions.rs, pallets/sminer/src/helper.rs, pallets/sminer/src/lib.rs, pallets/sminer/src/types.rs, pallets/storage-handler/src/lib.rs, standalone/chain/runtime/src/lib.rs
=> 0.7.6 miner reward

Cargo.lock, pallets/oss/Cargo.toml, pallets/oss/src/lib.rs, pallets/oss/src/types.rs, standalone/chain/runtime/src/lib.rs
=> 0.7.7 proxy auth

Cargo.lock, Cargo.toml, pallets/audit/Cargo.toml, pallets/reservoir/Cargo.toml, pallets/reservoir/src/impls.rs, pallets/reservoir/src/lib.rs, pallets/reservoir/src/types.rs, pallets/sminer/Cargo.toml, pallets/sminer/src/functions.rs, pallets/sminer/src/helper.rs, pallets/sminer/src/lib.rs, standalone/chain/runtime/Cargo.toml, standalone/chain/runtime/src/lib.rs
=> 0.7.7 reservoir

README.md
=> Update the URL of CESS

standalone/teeworker/cifrost/src/lib.rs, standalone/teeworker/cifrost/src/types.rs
=> hotfix: `MasterKey` occasionally fails to obtain

pallets/sminer/src/constants.rs, standalone/chain/runtime/src/lib.rs
- Modify the number of tokens released by the faucet each time.
=> 0.7.8 update faucet
